### ISSUE TITLE
Submit to AUR

### ISSUE THREAD

**Issue by b1f6c1c4** [b1f6c1c4/git-get#11]
- Readings:
    - [x] https://wiki.archlinux.org/index.php/Arch_package_guidelines
    - [x] https://wiki.archlinux.org/index.php/Arch_User_Repository
    - [x] https://wiki.archlinux.org/index.php/AUR_Trusted_User_Guidelines
    - [x] https://wiki.archlinux.org/index.php/AUR_submission_guidelines
- Documentation:
    - [x] man page
    - [x] List of dependents
- Stabilization:
    - ~~Switch to some unit-testing framework~~
    - ~~Coverage report~~
    - [x] Bug #8

**Comment by b1f6c1c4** [comment]
Published to [AUR](https://aur.archlinux.org/packages/git-get/). Copying @KevinZonda

**Comment by KevinZonda** [comment]
LGTM!
