### ISSUE TITLE
Package git-get-v0.0-1-any.pkg.tar.zst has no SUID files.

### ISSUE THREAD

**Issue by IoriOikawa** [b1f6c1c4/git-get#12]
This message occurs when Arch Linux is merging a newer version of git-get.

**Comment by b1f6c1c4** [comment]
Actually this is not a problem for `git-get`, nor for the AUR package `git-get`. It is the security feature built in some AUR helpers (like `rua`). See here for the documentation: https://github.com/vn971/rua#rua----
