### ISSUE TITLE
git get commit does not work

### ISSUE THREAD

**Issue by MohammadEglil** [b1f6c1c4/git-get#24]
When I would run the command `git get b1f6c1c4/git-get 2dd50b6` I would get the error `fatal: remote branch 2dd50b6 could not be found in upstream repository`. I have Mac OS and git get for repo and file worked well.

**Comment by b1f6c1c4** [comment]
@MohammadEglil Could you please attach the output from `git get -v b1f6c1c4/git-get 2dd50b6` command?

**Comment by MohammadEglil** [comment]
@b1f6c1c4 Thats what I got:

> mohammadeglil@Mohammads-MacBook-Pro ~ % git get -v b1f6c1c4/git-get 2dd50b6
> OCWD=/Users/mohammadeglil
> FORCE=''
> FORCE_DIR=''
> OUTPUT=/Users/mohammadeglil/git-get
> DEF_OUTPUT=YES
> PRESERVE=''
> TAG=''
> TAG_FILE=''
> GITHUB=REPO
> GH_REPO=b1f6c1c4/git-get
> REPO=git@github.com:b1f6c1c4/git-get.git
> BRANCH=2dd50b6
> DIR=''
> BASENAME=git-get
> PREV_TAGS=''
> WORK_DIR=/private/var/folders/41/1n8hp4_n7j523xwflsx1kpq80000gn/T/tmp.Y9uOHB6a
> git clone --bare --progress --branch 2dd50b6 --depth 1 --no-tags git@github.com:b1f6c1c4/git-get.git git-get/.git 
> Klone in Bare-Repository 'git-get/.git' ...
> Enter passphrase for key '/Users/mohammadeglil/.ssh/id_ed25519': 
> Warnung: Konnte zu klonenden Remote-Branch 2dd50b6 nicht finden.
> Schwerwiegend: Remote-Branch 2dd50b6 nicht im Upstream-Repository origin gefunden
> Error: No viable method.

This is german...I will change my terminal language to english

**Comment by MohammadEglil** [comment]
Funnily enough...by changing the system language everything worked properly. I will keep it english.

**Comment by b1f6c1c4** [comment]
Interesting. I will investigate this i18n-related issue.
