### ISSUE TITLE
git get commit causes error fatal: Remote branch <commit> not found in upstream origin

### ISSUE THREAD

**Issue by MohammadEglil** [b1f6c1c4/git-get#25]
I did not have a look at the log closely since git commands would work anyway, but I still get the error warning `fatal: Remote branch 2dd50b6 not found in upstream origin` I did install the latest version including the  i18n-related bug fix. When I would run `git get -v b1f6c1c4/git-get 2dd50b` I would get the following:

> 6
OCWD=/Users/mohammadeglil/desktop
FORCE=''
FORCE_DIR=''
OUTPUT=/Users/mohammadeglil/desktop/git-get
DEF_OUTPUT=YES
PRESERVE=''
TAG=''
TAG_FILE=''
GITHUB=REPO
GH_REPO=b1f6c1c4/git-get
REPO=git@github.com:b1f6c1c4/git-get.git
BRANCH=2dd50b6
DIR=''
BASENAME=git-get
PREV_TAGS=''
WORK_DIR=/private/var/folders/41/1n8hp4_n7j523xwflsx1kpq80000gn/T/tmp.4Qr9N2hF
git clone --bare --progress --branch 2dd50b6 --depth 1 --no-tags git@github.com:b1f6c1c4/git-get.git git-get/.git 
Cloning into bare repository 'git-get/.git'...
**warning: Could not find remote branch 2dd50b6 to clone.
fatal: Remote branch 2dd50b6 not found in upstream origin**
git clone --mirror --filter tree:0 --progress git@github.com:b1f6c1c4/git-get.git git-get/.git 
Cloning into bare repository 'git-get/.git'...
remote: Enumerating objects: 151, done.
remote: Counting objects: 100% (48/48), done.
remote: Compressing objects: 100% (48/48), done.
remote: Total 151 (delta 0), reused 48 (delta 0), pack-reused 103
Receiving objects: 100% (151/151), 24.76 KiB | 1.65 MiB/s, done.
Resolving deltas: 100% (15/15), done.
Got SHA1: 2dd50b6425c7d79f4695aa69d05467e1a00fc20f
git reset --hard 
remote: Enumerating objects: 2, done.
remote: Total 2 (delta 0), reused 0 (delta 0), pack-reused 2
Receiving objects: 100% (2/2), 280 bytes | 280.00 KiB/s, done.
remote: Enumerating objects: 3, done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 3
Receiving objects: 100% (3/3), 179 bytes | 179.00 KiB/s, done.
Updating files: 100% (6/6), done.
HEAD is now at 2dd50b6 use https
size used in /tmp = 148K	/private/var/folders/41/1n8hp4_n7j523xwflsx1kpq80000gn/T/tmp.4Qr9N2hF
tag = 2dd50b6425c7d79f4695aa69d05467e1a00fc20f

**Comment by b1f6c1c4** [comment]
It was the desired behavior prior to commit https://github.com/b1f6c1c4/git-get/commit/dbc92194e9cd9db19553b409978d07e98e8e1aa6. If you upgrade to a newer version of git-get you won't see the error messages.

**Comment by MohammadEglil** [comment]
I did upgrade but the commit `dbc9219` is not in the latest release. Would be cool if you would include this commit in your latest release.
